# Generated by Django 6.0 on 2025-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Haftakun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=100)),
                ("dam_olish", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kurs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=150)),
                ("narxi", models.DecimalField(decimal_places=2, max_digits=10)),
                ("aktivligi", models.BooleanField(default=True)),
                ("boshlanish_sanasi", models.DateTimeField()),
                ("tugash_vaqti", models.DateTimeField()),
                ("oquvchilar_soni", models.IntegerField()),
                ("rasmi", models.ImageField(upload_to="kurslar/")),
                ("yaratilgan_vaqt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Oquvchi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ismi", models.CharField(max_length=150)),
                ("familya", models.CharField(max_length=150)),
                ("yosh", models.IntegerField()),
                ("rasmi", models.ImageField(upload_to="oquvchilar/")),
                ("maktabda_oqiydimi", models.BooleanField(default=True)),
                ("yaratilgan_vaqt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
